#############################################################################
# Makefile for building: VREPClient
# Generated by qmake (2.01a) (Qt 4.8.7) on: qui mar 30 21:30:06 2017
# Project:  VREPClient.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile VREPClient.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DMAX_EXT_API_CONNECTIONS=255 -DNON_MATLAB_PARSING -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -D_REENTRANT $(DEFINES)  -std=c++11
CXXFLAGS      = -m64 -pipe -O2 -Wall -D_REENTRANT $(DEFINES)  -std=c++11
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4 -I../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/remoteApi -I../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/include -I../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/common -I.
LINK          = g++
LFLAGS        = -m64 -pthread -Wl,-no-as-needed -ldl -O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/remoteApi/extApi.c \
		Main.cpp \
		Robot.cpp \
		Simulator.cpp \
		../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/remoteApi/extApiPlatform.c \
		../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/common/v_repLib.cpp 
OBJECTS       = extApi.o \
		Main.o \
		Robot.o \
		Simulator.o \
		extApiPlatform.o \
		v_repLib.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		VREPClient.pro
QMAKE_TARGET  = VREPClient
DESTDIR       = 
TARGET        = VREPClient

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: VREPClient.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile VREPClient.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile VREPClient.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/VREPClient1.0.0 || $(MKDIR) .tmp/VREPClient1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/VREPClient1.0.0/ && $(COPY_FILE) --parents ../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/include/v_repLib.h Robot.h Simulator.h .tmp/VREPClient1.0.0/ && $(COPY_FILE) --parents ../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/remoteApi/extApi.c Main.cpp Robot.cpp Simulator.cpp ../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/remoteApi/extApiPlatform.c ../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/common/v_repLib.cpp .tmp/VREPClient1.0.0/ && (cd `dirname .tmp/VREPClient1.0.0` && $(TAR) VREPClient1.0.0.tar VREPClient1.0.0 && $(COMPRESS) VREPClient1.0.0.tar) && $(MOVE) `dirname .tmp/VREPClient1.0.0`/VREPClient1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/VREPClient1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

extApi.o: ../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/remoteApi/extApi.c ../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/remoteApi/extApi.h \
		../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/remoteApi/extApiPlatform.h \
		../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/remoteApi/extApiInternal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o extApi.o ../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/remoteApi/extApi.c

Main.o: Main.cpp Robot.h \
		Simulator.h \
		../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/remoteApi/extApi.h \
		../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/remoteApi/extApiPlatform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Main.o Main.cpp

Robot.o: Robot.cpp Robot.h \
		Simulator.h \
		../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/remoteApi/extApi.h \
		../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/remoteApi/extApiPlatform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Robot.o Robot.cpp

Simulator.o: Simulator.cpp Simulator.h \
		../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/remoteApi/extApi.h \
		../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/remoteApi/extApiPlatform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Simulator.o Simulator.cpp

extApiPlatform.o: ../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/remoteApi/extApiPlatform.c ../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/remoteApi/extApiPlatform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o extApiPlatform.o ../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/remoteApi/extApiPlatform.c

v_repLib.o: ../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/common/v_repLib.cpp ../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/include/v_repLib.h \
		../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/include/v_repConst.h \
		../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/include/v_repTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o v_repLib.o ../V-REP_PRO_EDU_V3_3_2_64_Linux/programming/common/v_repLib.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

